- wp-content/plugins/cms-tree-page-view-extensions/cms-tree-page-view-extensions.php
> show tree view as default view

- wp-content/plugins/editor-next-button/editor-next-button.php
- wp-content/plugins/editor-next-button/next-button.js
- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
> Next button

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
> adjust cover image size

- wp-content/plugins/project-user-roles/plugin.php
> Allow all roles to create_and_download_pdf

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
Use Integreat yellow for now.
resolves #178
> Return color for every instance

- wp-content/plugins/automatic-translation/TranslationManager.php
move to new accept method
resolves #202
> Only translate pages and events

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_ModifiedContent.php
Quick Fix for #27 - users can now still click "Delete permanently", however it will have no effect.
> Replace delete action with trash in delete_link

- wp-content/plugins/project-user-roles/plugin.php
- wp-content/plugins/separate-disclaimer/plugin.php
not multilanguage-activated by default so far - need to go into translation options
> Separate Disclaimer

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
> Darken returned multisite color

- wp-content/plugins/automatic-translation/TranslationManager.php
- wp-content/plugins/wp-api-extensions/endpoints/RestApi_ModifiedContent.php
Introduce output_post filter in RestAPI_ModifiedContent, hook in with TranslationManager
resolves #226
> Remove disclaimer text, output automatic translation flag

- wp-content/plugins/project-user-roles/plugin.php
Adds a capability for clickguide (#278) to user role "manager".
> Update project user roles

- wp-content/plugins/automatic-translation-button/callback.php
- wp-content/plugins/automatic-translation-button/js/automatic-translation-button.js
- wp-content/plugins/automatic-translation-button/plugin.php
> Reload on automatic translation button click instead of AJAX

- wp-content/plugins/wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
added json properties for page url
> Wp api extension

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
REST API: blog is live if and only if the public flag is set #344
> REST API: blog is live if and only if the public flag is set #344

- wp-content/plugins/ig-remove-403-forbidden/plugin.php
> admin_page_access_denied HTTP Status 200

- wp-content/plugins/ig-remove-403-forbidden/plugin.php
If a user does not select a city for login, it is not required to show him an error page. A friendly city selection is better.
> Changed description from error page to city selection

- wp-content/plugins/wp-rtl/readme.txt
- wp-content/plugins/wp-rtl/wp-rtl.css
- wp-content/plugins/wp-rtl/wp-rtl.php
Provides Left To Right and Right To Left buttons for the TinyMCE editor.
> WP RTL Plugin

- wp-content/plugins/ig-customize-editor-integreat/customize-editor-integreat.php
Reduces complexity of the TinyMCE editor.
> Customized editor plugin

- wp-content/plugins/ig-content-loader-base/plugin.php
- wp-content/plugins/ig-content-loader-instance/plugin.php
- wp-content/plugins/ig-content-loader-sprungbrett/plugin.php
Provides Content Loader plugins
* Base (supports handling foreign content)
* Sprungbrett (using BBW Sprungbrett API)
* Instance (loading pages from other blogs within the same wordpress installation)
> Content Loader Base, Instance and Sprungbrett

- wp-content/plugins/ig-customize-editor-integreat/customize-editor-integreat.php
Added LTR und RTL buttons to cutomized editor plugin.
> Add LTR and RTL buttons to TinyMCE

- wp-content/themes/integreat-webview-sites/includes/cookies.php
Stops redirect after login due to language cookie set by web view
> Login fix after use of web view

- wp-content/plugins/ig-content-loader-base/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
enables content loader to modify post content in rest api
> new hook in rest api extension before post preparation

- wp-content/plugins/ig-content-loader-base/plugin.php
Just removed a ?> at the end of the plugin.php
> fixes #412

- wp-content/themes/integreat-webview/style.css
Fixes not visible flags for language selection in WebView.
> IE WebView flags fix

- readme.html
- wp-admin/about.php
- wp-admin/includes/class-wp-upgrader.php
- wp-admin/includes/media.php
- wp-admin/includes/upgrade.php
- wp-includes/version.php
> Security fixes of WP 4.4.5

- .gitignore
- wp-content/plugins/ig-customize-login-integreat/customize-login-integreat.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
> Hotfix (#456)

- wp-content/themes/integreat-webview/functions.php
Now themes need to declare, that they support featured images:
https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
> fixed featured image

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* fixes #458
* let WP prepare posts
> Bugfix/issue#458 (#464)

- wp-content/plugins/ig-extras/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/RestApi_Multisites.php
* plugin that proves blog options for additional services
* added hook in wp api extension
> Ingegreat ecosystems extras settings, fixes #405

- wp-content/plugins/ig-extras/plugin.php
* shortened ig-extras strings
* added careers4refugee
* dont delete options on deactivation
> Careers for Refugees, fixes 440

- wp-content/plugins/ig-automatic-translation/TranslationService.php
- wp-content/plugins/ig-text-dir/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_WpmlLanguages.php
Squashing directly so that i can test it on develop (API key)
> automatic translation returns RTL content for ar and fa, fixes #438

- wp-content/plugins/ig-menu-help/plugin.php
> added link to https://hilfe.integreat-app.de/q2a, fixes #398

- wp-content/plugins/ig-wpml-lock-media-checkboxes/js/lock-wpml-media-checkbox.js
- wp-content/plugins/ig-wpml-lock-media-checkboxes/plugin.php
> lock wpml media checkboxes, fixes #260

- wp-content/plugins/ig-simplify-ui/css/ig-event-ui.css
- wp-content/plugins/ig-simplify-ui/css/ig-postmeta.css
- wp-content/plugins/ig-simplify-ui/plugin.php
* hides translation of post meta
* hides not useful boxes in events creation
> hide elements, fixes #403, partially #406

- wp-content/plugins/ig-extras/plugin.php
added ig-zip in ig-extras plugin
> added zip code to ig-extras, fixes #513

- wp-content/plugins/ig-mobile-preview/js/copy-content.js
- wp-content/plugins/ig-mobile-preview/plugin.php
- wp-content/plugins/ig-wp-api-extensions/plugin.php
* super admins can delete pages, fixes #531 
* has to be used with caution
* wpautop mobile preview, fixes #40 
* uses simple REST API to transform content with wpautop
> Delete pages, mobile preview

- wp-content/plugins/ig-mobile-preview/js/copy-content.js
* Use wpautop api
* issue: Kills HTML elements in text
> Fixes mobile preview POST variable

- wp-content/plugins/ig-mobile-preview/js/copy-content.js
Only create preview when loading page.
> preview only on page load, fixes #550

- wp-content/plugins/ig-domainfix/plugin.php
Domains could be moved to config.ini.
> Replace vmkrcmar21 domain in outgoing mails, fixes #555

- wp-content/plugins/ig-mobile-preview/js/copy-content.js
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* Replace vmkrcmar21 domain in outgoing mails, fixes #555
* API empty string for all pages with children, fixes #557 (#558)
> Mail URLs, empty string in API

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* Text allowed for pages having children
> Text allowed for pages having children (#561)

- wp-content/plugins/ig-extras/plugin.php
@thimmy687 these are the names of the extras for the IHK.
$ig_extras_settings['ige-ilb'] = "0";	// IHK Lehrstellenboerse
$ig_extras_settings['ige-ipb'] = "0";	// IHG Praktikumsboerse
> IHK Lehrstellenboerse / Praktikumsboerse

- wp-content/plugins/ig-extras/plugin.php
ige-ilb: IHK Lehrstellenboerse
ige-ipb: IHK Praktikumsboerse
> IHK Lehrstellenboerse / Praktikumsboerse (#567)

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
No frontend is using this data and we want to protect privacy as much as possible.
> Removed author from API

- wp-activate-plugins.sh
- wp-content/plugins/ig-hide-preview-button/plugin.php
This just hides the preview button because this functionality is broken due to the new webapp.
Fixing this would require to expose the changes through the REST api. Not sure if it's worth it :/
> Add plugin to hide preview button

- wp-content/plugins/ig-nuernberg-calendar/em-event-wrapper.php
- wp-content/plugins/ig-nuernberg-calendar/plugin.php
* Imported events are stored as drafts
* date for all event types is imported correctly in "single event"-mode
> NueCal: fixed date import and draft status

- wp-content/plugins/ig-dashboard-widget/plugin.php
Just a light-weight addition to our Dashboard. Future goal might be using it to Link to our Wiki
> Adding Integreat-Welcome-Widget to our dashboards

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedEvents.php
> Adding recurring events to API

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* Left JOIN produces more results than we like
> Fix 'API shows all languages at once'

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* Left JOIN produces more results than we like
> Fix 'API shows all languages at once' (#623)

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
use the working filter ap_post_to_foreign_language_id to check whether the available_language_url makes sense. (fixes #638)
> fix available urls in api

- wp-content/plugins/firebase-notifications/LICENSE
- wp-content/plugins/firebase-notifications/README.md
- wp-content/plugins/firebase-notifications/plugin.php
- wp-content/plugins/firebase-notifications/service.php
- wp-content/plugins/firebase-notifications/settings.php
- wp-content/plugins/firebase-notifications/templates/network_settings.php
- wp-content/plugins/firebase-notifications/templates/settings.php
Copied current version from https://github.com/Integreat/wp-ms-firebase-cloud-messaging
> Add title prefix to FCM plugin, fixes #658

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Children.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Parents.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Relatives_Abstract.php
- improve the structure of the children & parents endpoint
- fixed the bug that the root pages can not be fetched through the children endpoint
> [api-v3] improve parents & children endpoints (fixes #696)

- robots.txt
Allow crawlers to access the API.
> Add robots.txt, fixes #712

- .htaccess
-Adds extra condition to .htaccess to prevent Internal-Redicrec-Loops
-
**Fixes**: #
> Hotfix to prevent Rewrite-Loop

- wp-content/plugins/cms-tree-page-view/functions.php
- wp-content/plugins/ig-plugin-adjustment/plugin.php
- wp-content/plugins/ig-revisions/plugin.php
* Add warnings for active revisions
* Only verwalter can set revisions
* Tree view displays active revisions
> Change Integreat Revisions, fixes #757

- wp-content/plugins/ig-revisions/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php
- fixes a bug which caused the api to return only hashes
- remove user check
> [ig-revisions] fix api filter

- wp-content/plugins/ig-attach-content/plugin.php
- wp-content/plugins/ig-cms-tree-page-view-extensions/cms-tree-page-view-extensions.php
* Replace count() with strlen() for strings
> Fix tree view labels

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
* Remove rewrite of event type from 'event' to 'event-recurring'
> HOTFIX: Change REST API v0/v1

- wp-content/themes/integreat-webview-sites/index.php
- wp-content/themes/integreat-webview/index.php
- Closes #800 
Redirect with status code 301
> Redirect to webapp with status code 301 for permanent redirect

- wp-content/plugins/ig-revisions/plugin.php
* Follow the Wordpress Codex PHP Coding Standards
* Comment all functions
> Change ig-revisions plugin

- wp-content/plugins/ig-revisions/plugin.php
prevents unauthorized changes of the live content
- before delivering a prior revision, check if the revision was a wordpress autosave
Fixes #810
> [ig-revisions] fix #810

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
> sitemap bugfixes

- wp-content/plugins/ig-simplify-ui/plugin.php
- remove posts from admin menu
> [ig-simplify-ui] remove posts from admin menu

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedEvents.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedEvents.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
- remove past events from api results
> [api] remove past events from api results

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
- remove array keys on site endpoint
Fixes: #832
> [api-v3] remove array keys on site endpoint (fixes #832)

- wp-content/plugins/wpml-translation-management/classes/class-wpml-tm-api.php
- disables translation permission management on user and language basis
- instead, all roles are allowed to create and edit translations
> [wpml] hotfix for translation capabilities

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
adds the language to the url & path of events if missing
Fixes: #855
> [api-v3] insert languages into event url (fixes #855)

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
> [api-v3] fix languages in event urls

- wp-content/mu-plugins/ig-ure-media-list.php
- Deactives the custom filter of User Role Editor to make the total media-library visible to all user
Fixes #851
> Use filter to show full media list

- wp-content/plugins/broken-link-checker/core/core.php
- wp-content/plugins/ig-plugin-adjustment/plugin.php
* Verwalter need to be able to access the broken link checker.
* Bind access to create_user capability.
* Add changed capability to ig-plugin-adjustment.
* Fixes #872
> Change capability for broken-link-checker

- wp-content/plugins/ig-wp-api-extensions/endpoints/v1/RestApi_Multisites.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites_Hidden.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites_Live.php
* Remove default limit of 100 sites returned when
calling get_sites(). We have more than 100 active
sites now.
* Fixes #846.
> Change REST API get_sites()

- wp-content/plugins/firebase-notifications/classes/database.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v1/RestApi_Multisites.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites_Hidden.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites_Live.php
* Remove default limit of 100 sites returned when
calling get_sites(). We have more than 100 active
sites now.
* Fixes #846.
> Fix REST API sites limit

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php
> [api-v3] enable path support for posts diff (resolves #893)

- wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php
> [ig-mpdf] trim path if beginning with slash (fixes #895)

- .htaccess
* Make wp-activate.php accessible.
* Redirect to web.integreat-app.de instead of
index.php.
> Improve rewrite rules in htaccess

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
Don't include recuring events twice in case the first event query already contains recurring events (I determined this by checking whether there is an event with `recurrence_id !== null`.
**Fixes**: #911
> [api] remove duplicate recurring events (fixes #911)

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
> [ig-sitemap] adapt url to new web-app domain

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
> remove duplicate recurring events & adapt sitemap url

- wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php
This resolves an error where the url parameter of the pdf api was invalid.
> [ig-mpdf] fix bug with invalid url parameter

- wp-content/plugins/sitepress-multilingual-cms/res/js/post-edit-languages.js
* Apply Patch 0004
@Ponitac @timoludwig not sure who authored this patch initially. But it was not in develop, so I patched it. Is this correct?
> Fix Recurring Events + Sitepress

- wp-content/plugins/wpml-translation-management/classes/user/class-wpml-translator-admin-records.php
* Apply patches/0001
* Fixes #840
> Fix translation mgmt roles

- .htaccess
* No further redirects if path to wp-include, wp-content,
or wp-admin.
* Add redirect for /newbloguser/ URLs, fixes #917.
> Fix htaccess

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
* Some blogs have mixed working and non-working
recurring events. Therefore merge all events
into one array and then remove duplicates.
> Change APIv3 Events endpoint

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
* Add timezone of event in tz name format
* Fixes #927
> Add event time zone

- wp-content/themes/twentyfifteen/comments.php
- wp-content/themes/twentyfifteen/content-link.php
- wp-content/themes/twentyfifteen/content-page.php
- wp-content/themes/twentyfifteen/content.php
- wp-content/themes/twentyfifteen/css/blocks.css
- wp-content/themes/twentyfifteen/css/editor-blocks.css
- wp-content/themes/twentyfifteen/functions.php
- wp-content/themes/twentyfifteen/header.php
- wp-content/themes/twentyfifteen/image.php
- wp-content/themes/twentyfifteen/inc/back-compat.php
- wp-content/themes/twentyfifteen/inc/custom-header.php
- wp-content/themes/twentyfifteen/inc/customizer.php
- wp-content/themes/twentyfifteen/inc/template-tags.php
- wp-content/themes/twentyfifteen/readme.txt
- wp-content/themes/twentyfifteen/search.php
- wp-content/themes/twentyfifteen/style.css
Update the Twenty Fifteen theme to version 2.3.
> Update Twenty Fifteen to 2.3

- migrate-database.php
* URLs need to be changed in the wp_x_options.
> Fix database migration

- wp-content/plugins/ig-push-content/plugin.php
* Limit number of tries for authentication via Push API
to a maximum of 5. Counter is reset if the correct token
is used with a counter smaller than 5. Once it reaches 5,
the auth is permanently disabled.
> Limit token auth tries with push api

- .htaccess
* Deny access to comment.php due to CSFR vulnerability.
> Deny access to wp-includes/comment.php

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
sanitizes text comments arriving via the API
> [ig-feedback] sanitize feedback text

- .htaccess
* Deny access to RPC API for security reasons.
> Deny access to xmlrpc.php

- .htaccess
* Disallowing access to comment.php does not work for
fixing a vulnerability.
> Remove access control for comment.php

- wp-content/plugins/ig-fix-comment/plugin.php
* Disallow posting any content via the normal Wordpress
comment function to fix CVE-2019-9787.
> Disable normal comment content

- wp-content/plugins/ig-customize-login-integreat/customize-login-integreat.php
* Remove period at the end of message.
> Change syslog log in messages

- .htaccess
* Add syslog logging on (failed) log ins. For failed log in attempts, the IP of the connecting client is logged.
> Add logging of log ins

- config.ini
- wp-config.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
* Setting for enabling tracking on specified systems.
This is necessary to better work with live DB dumps.
> Add setting to enable tracking

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
* Add a syslog message on API calls with X-Integreat-Development header.
> Add syslog for X-Integreat-Development header

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
Fix Development header with syslog message
> Fix Development header syslog

- wp-content/plugins/ig-fix-comment/plugin.php
Fix non-empty output buffer which prevents downloading files.
> Fix non-empty output buffer

- wp-content/plugins/ig-mpdf/IntegreatMpdf.php
ig-mpdf requires a tmp directory. Create the directory if it does not exist.
> [ig-mpdf] Create tmp dir on use

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
IG setting float return null if null
> IG setting float return null if null

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
Rename Aliases from city-aliases to aliases.
> Rename city aliases setting

- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
* If the user does not enter an empty JSON object, we
the plugin can assume that {} is okay.
> Change IG Settings empty JSON value

- wp-content/plugins/ig-mpdf/IntegreatMpdf.php
> Add attach content in PDF creation, fixes #985

- wp-content/plugins/ig-menu-help/plugin.php
* Send users directly to knowledge base
> Change Integreat Wiki link

- wp-content/plugins/firebase-notifications/css/wp-ms-fcm.css
> Fix PN Editor, fixes #1014

- wp-content/plugins/firebase-notifications/plugin.php
Requires create_users, which is a manager permission.
> Change FCM Menu permissions, fixes #1008

- wp-content/plugins/ig-project-user-roles/plugin.php
> Allow managers to edit media, fixes #1011

- wp-content/plugins/ig-feedback/plugin.php
> Change feedback name, fixes #1015

- wp-content/plugins/ig-attach-content/plugin.php
Adds a max width for images in attach content preview
**Fixes**: #1022
> Change attach content preview, fixes #1022

- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
I simply adjusted the url/path to the media-field.js as using `__DIR__` seems not to work in the test/production system.
> Enhancement PDF export: Bugfix JS file path

- wp-content/plugins/firebase-notifications/functions/rest_api.php
> Fix PN API typo

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
> Add tunews to site settings

- wp-content/plugins/firebase-notifications/classes/database.php
- wp-content/plugins/firebase-notifications/functions/rest_api.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_FCM.php
Add filter to push news addpoint that allows filtering for a single push news item.
> Add single push news filter

- wp-content/plugins/ig-settings/classes/IntegreatSetting.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v1/RestApi_Multisites.php
* Rename push-notifications to push_notifications in sites endpoint
> Rename push news enable property

- wp-content/plugins/firebase-notifications/classes/database.php
- wp-content/plugins/firebase-notifications/functions/rest_api.php
- wp-content/plugins/ig-settings/classes/IntegreatSetting.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v1/RestApi_Multisites.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_FCM.php
- Change sites endpoint
- Add single Push News filter
> Change Push News API

- wp-admin/about.php
- wp-includes/cache.php
- wp-includes/class-wp-customize-manager.php
- wp-includes/class-wp-query.php
- wp-includes/class-wp.php
- wp-includes/formatting.php
- wp-includes/functions.php
- wp-includes/http.php
- wp-includes/kses.php
- wp-includes/pluggable.php
- wp-includes/post.php
- wp-includes/rest-api.php
- wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php
- wp-includes/user.php
- wp-includes/version.php
> Update Wordpress to 4.9.14

- wp-content/plugins/ig-simplify-ui/plugin.php
- Remove "Available Tools" / "Verfügbare Werkzeuge"
**Fixes**: WP-2
> Remove available tools submenu, fixes WP-2

- wp-content/plugins/firebase-notifications/functions/rest_api.php
> FCM API: show old messages for 4 weeks

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
* Add `pois` property to sites endpoint
> Add enable POIs API setting, fixes WP-9

- PULL_REQUEST_TEMPLATE.md
- wp-content/plugins/events-manager/admin/em-admin.php
- Remove pending events counter from Events Manager menu item
- Add patch
> Remove Events Manager menu counter

- patches/0005-Events-Manager-remove-menu-counter.patch
> Add Events Manager patch

- wp-content/plugins/ig-svg-support/plugin.php
> Add SVG support plugin

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
- wp-content/plugins/tinymce-no-translate/plugin.php
Allow translate attribute for span
> Allow translate attribute for span

- wp-content/plugins/ig-customize-editor-integreat/customize-editor-integreat.php
- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
- wp-content/plugins/tinymce-no-translate/plugin.php
* Remove sitemaps for inactive sites
* Enable draft and private pages as parents
> Change parent pages, sitemap

- wp-content/plugins/firebase-notifications/classes/service.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_FCM.php
Use the region slug in the topics path instead of the internal blog ID.
> Change Push News topics path, fixes WP-25

- wp-content/plugins/ig-menu-help/plugin.php
> Integreat Wiki link in main menu, fixes WP-29

- wp-content/plugins/tinymce-no-translate/no-translate.css
- wp-content/plugins/tinymce-no-translate/no-translate.js
Introduces the same functionality as https://github.com/Integreat/integreat-cms/pull/601
> Improve no translate function

- wp-content/plugins/ig-attach-content/plugin.php
> Sort live content blogs by path

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
Add the Integreat setting bounding_box as a region property.
**Fixes**: #WP-42
> Add bounding_box to API, fixes WP-42

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Children.php
Add a depth parameter to the children endpoint and use a recursive descendants function for gathering the result pages.
> Change APIv3 children endpoint, fixes WP-43

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Children.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Pages.php
* Randomize last 16 bit of IP address to prevent collisions.
* Collect original user agents instead of parsing web or  native strings.
> Change API tracking

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Base_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Relatives_Abstract.php
* Remove WPML url_to_postid filter function during API parameter validation as it returns false results.
> Change relative API endpoints, fixes WP-45

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Post.php
* remove WPML filters for feedback permalink validation
> Change feedback API link validation

- .htaccess
- export-database.php
* regions export
* languages
* language tree
* pages and page translations
* live content
* images
* page icons
* users
* password hashes
* events
* special rules for languages
```bash
#!/bin/bash
#find . -type f -regex '^.*\(png\|gif\|jpg\|jpeg\|JPEG\|JPG\)$' -not -path "*/thumbnail/*" -exec /usr/local/bin/create-thumbnail.sh {} \;
THUMBNAIL_PATH=$(dirname $1)
IMAGE_NAME=$(basename $1)
THUMBNAIL_PATH="$THUMBNAIL_PATH/thumbnail"
echo "CREATING $THUMBNAIL_PATH/$IMAGE_NAME"
mkdir -p "$THUMBNAIL_PATH"
convert -thumbnail x300 "$1" "$THUMBNAIL_PATH/$IMAGE_NAME"
```
> Add export to Django fixtures

- export-database.php
Fix some consistency issues in the Django fixtures export script.
> Fix Django export issues

- export-database.php
Fixes https://github.com/digitalfabrik/integreat-cms/issues/1118
> Export: apply wpautop() to post content

- export-database.php
- Fix country codes of languages
- Fix `administrative_division_included` field of regions 
Again, didn't test it, but I hope it works this time...
> Improve data export

- export-database.php
- Fix export of all languages
- Add a slug mapping file
- Add placeholder values for MediaFile attributes
> Deploy improved export script

- export-database.php
Do not export page content when it is duplicated from another language, fixes [WP-65](https://issues.tuerantuer.org/browse/WP-65)
> Export: skip duplicated content, WP-65
