- wp-content/plugins/separate-disclaimer/wpml-config.xml
Add wpml-config.xml
Note: The translatability is only activated after visiting the WPML translation options once so far.
> Make disclaimer translatable

- wp-content/plugins/wp-api-extensions/endpoints/RestApi_Multisites.php
Replace flag "live" with wordpress standard.
If a website is marked as public by admin,  live parameter would be true.
> Check public key for live websites

- wp-content/plugins/ig-mobile-preview/css/mobile-preview.css
- wp-content/plugins/ig-mobile-preview/js/copy-content.js
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
Currently the API is stripping p-tags with its styles. This behaviour removes LTR and LTR attributes which are needed when working with arabic texts.
This pull request together with https://github.com/Integreat/app-android/pull/195 leaves p-tags in and only replaces \\n with \<br\>.
For better viewing, a paragraph spacing of 0.8em is inserted.
> WP API formatting

- wp-activate-plugins.sh
- wp-content/plugins/ig-plugin-adjustment/plugin.php
It adds code to the cms-tree-page-view plugin to work with revisionary
resolves #435
> Add plugin that automatically runs when WordPress plugins are updated

- wp-content/plugins/cms-tree-page-view/functions.php
I forgot this in #436.
Will be unnecessary in the future with #446
> Re-add line to mark revisionary pages as pending in tree-page-view

- wp-content/plugins/ig-wpml-lock-media-checkboxes/js/lock-wpml-media-checkbox.js
Disabling checkboxes removes them from the POST data. Now we're using a hook and disable events when clicking.
> Do not disable checkbox, fixes #549

- wp-includes/class-wp-editor.php
Hotfix / Workaround for `Failed to load content css: https://cms.integreat-app.de/augsburg/wp-includes/js/tinymce/skins/wp-content.css?ver=4.8.3` error message. The CSS file does not seem to be important. Hopefully it works with the next version.
> Fix TinyMCE CSS error message (workaround)

- wp-activate-plugins.sh
* Not needed for nomal pages, could later be reused for events
> Deactivate automatic translation plugins, fixes #599

- wp-content/plugins/ig-plugin-adjustment/plugin.php
- wp-content/plugins/sitepress-multilingual-cms/res/js/post-edit-languages.js
Keep the scope when using language filter in the event list (at the moment the scope setting gets lost).
> Bugfix - event scope

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_Extras.php
- wp-content/plugins/ig-wp-api-extensions/plugin.php
this adds the new api v0 endpoint "extras". due to the database structure, the response format is not handled by the api, but in the backend instead (the api response includes the value field of every extra in the settings page). it depends on consistent and correct json-formatting in the backend. proposed format:
```
{
"name": [string],
"type": [string],
"enabled": [boolean],
"extension": {
"url": [string]
}
}
```
once the extra-settings are adapted, this should fix #619.
> add extras to api v0

- wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php
- displays pages in the correct order (fixes #692)
- includes all children of a page (and not only the direct children)
- only generates pdfs of published pages
> [ig-mpdf] improvements (fixes #692)

- wp-content/plugins/ig-settings/classes/IntegreatExtra.php
- wp-content/plugins/ig-settings/classes/IntegreatExtraConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSetting.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
At the moment, all input strings are encoded with `htmlspecialchars()` before storing input in the database to prevent XSS. This resulted in #694 and I solved it by storing the input in the database unescaped and escape it before printing.
> [ig-settings] change encoding of input values (fixes #694)

- wp-content/plugins/ig-mpdf/IntegreatMpdf.php
- wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php
- wp-content/plugins/ig-mpdf/IntegreatMpdfSettings.php
- wp-content/plugins/ig-mpdf/css/styles.css
- wp-content/plugins/ig-mpdf/custom.js
- wp-content/plugins/ig-mpdf/plugin.php
- refactor ig-mpdf (uses the php-inbuilt function `filemtime()` instead of the custom sql-tables to determine the modified timestamp of the pdf files)
- generate a table of contents if the pdf of a a category is generated via the webapp
- add the option to generate a table of contents if the pdf is generated via the cms backend (resolves #711)
> refactor ig-mpdf and add table of contents

- wp-content/plugins/ig-mpdf/IntegreatMpdf.php
- wp-content/plugins/ig-mpdf/css/pdf.css
At the moment the table of contents of our mpdf-plugin does not support subpages which have 3 or more ancestors (they are shown as top-level-pages).
I solved this by adding some custom css for the pdf file, which increases the left margin of entries by 2em per level.
> [ig-mpdf] support more levels in toc

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Languages.php
At the moment, wpml returns the languages in a weird object with language codes as keys (which is redundant because they are already contained in the values). To stay consistent with the other endpoints, we reset the array keys, which results in a json-list instead of an object.
> [api-v3] return language list instead of object

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
* To deactivate tracking for a blog, first set token to empty string, then deactivate plugin
> Fix deactivate single blog API tracking

- wp-admin/includes/class-wp-comments-list-table.php
- wp-content/plugins/ig-feedback/plugin.php
- wp-content/plugins/ig-feedback/script.js
- wp-content/plugins/ig-feedback/stylesheet.css
- wp-content/plugins/ig-plugin-adjustment/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Base_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Categories.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Cities.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Events.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Extra.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Extras.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Post.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Search.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Post.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Relatives_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/plugin.php
- provides three new APIv3 endpoints to post feedback to pages, events, extras, search results, cities and categories
- we use the comment functionality to implement feedback to pages and events
- we use comments to post with id 0 to indicate feedback about anything other than a post
- introduce an up- and down-voting counter
- text, rating, extra alias and search query are stored in custom comment meta fields
- change the structure of ig-plugin-adjustments to make it abstract
**Fixes:** #661:
> [ig-feedback] add APIv3 feedback endpoint for comments

- wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php
- removes the empty entry when generating PDFs for a whole instance
- when the page ids for the pdf are generated, the page id 0 is also in the array what causes an empty entry in the TOC and the PDF's content. This is caused by a wrong usage of `array_slice()` (in fact, the function did exactly nothing before the patch) and I fixed it by changing the offset, which has the effect that the first value of the array (which is 0) will be removed.
Fixes: #735
> [ig-mpdf] remove empty entry in TOC (fixes #735)

- wp-content/plugins/ig-wp-api-extensions/endpoints/RestApi_ExtensionBase.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php
- pages with an unpublished parent are no longer delivered via the API
- use a recurrent function to get all pages. This way, only the children of published pages are considered and all children of unpublished pages are ignored.
- in APIv3, we can use the recurrent function directly to fetch the posts
- in APIv0/v2, we have to use the recurrent function to get all page ids and test if each query result is contained in the post id array
Fixes: #655
> [api] only return pages with published ancestors (fixes #655)

- wp-content/plugins/ig-revisions/plugin.php
Revision meta box is only shown on page edits.
- Change add_meta_box parameter
**Fixes**: #
N/A
> Display revisions meta box only for pages

- wp-content/plugins/ig-attach-content/plugin.php
This plugin allows attaching the page of any other blog to the currently edited page. The foreign page can be attached to the beginning or end of the content.
Design:
- Add a meta box to the edit page dialog
- The meta box displays all blogs and pages of this blog in the currently selected language in two drop down lists
- 2 radio buttons select whether the content is attached before or after the content of the edited page
- When the page is saved, the values of the drop down lists and radio buttons is stored as post meta
- On plugin activation settings from content-loader-instance are migrated
- Add new and independent plugin based on content loader code
**Fixes**: #758
> Attach Content plugin

- wp-content/plugins/ig-settings/classes/IntegreatExtra.php
- wp-content/plugins/ig-settings/classes/IntegreatExtraConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
- adds the possibility to add more variable fields for the wohnraumbörse
- adds new placeholder `wb_name`, `wb_url` and `wb_api` which can be used in the extra fields to support variable values in the wohnraumbörse extra
Fixes: #796
> [ig-settings] add variable fields for wohnraumboerse (fixes #796)

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedContent.php
This removes user information from APIv0, v0 and v1 database queries. This information is not used in the API content and is therefore not required. The query results in content not being delivered if there are database inconsistencies with user IDs.
Fixes #806
> Remove user information from APIv0 to 2, fixes #806

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
for some reason, the old database query does not retrieve the correct languages for each city. this resulted in outdated languages in the sitemap index.
- use the wpml filter instead of a custom sql query
- don't include languages which have no translated pages
Fixes #803 
Fixes #815
> [ig-sitemap] remove old languages from sitemap index (fixes #803)

- wp-content/plugins/ig-wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v2/RestApi_ModifiedContent.php
- includes recurring events in api versions 0 - 2
- make the sql query for recurring events working again
- perform filter for pages with unpublished parents before the recurring events are fetched (unfortunately, wpml hooks into the query, which caused problems with the filter and recurring events)
Fixes #852
> [api-events] include recurring events in APIv0-2 (fixes #852)

- wp-content/plugins/ig-settings/classes/IntegreatSetting.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Sites.php
* This adds the 'city-aliases', 'long' and 'lat' properties
to the sites endpoint.
* 'long' and 'lat' contain the longitude and latitude of the
approximate geographic center of the county/city.
* The 'city-aliases' can contain smaller municipalities within
the county or city. For each alias, a longitude and latitude
must be provided as well. To reduce load on the apps, the
JSON is decoded to an object first, to integrate with the
overall endpoint JSON.
* Fixes #865
The change is also added to the wiki page: https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#response
> Add City Aliases and coordinates

- wp-content/plugins/ig-project-user-roles/plugin.php
* In multisites, the role remove_users is required to
remove a user from a blog. However, the user will not
be removed from the database. This can only be done
with the manage_network_users capability.
* Fixes #860
> Allow Verwalter to remove users

- .htaccess
* Deny access to migrate-database.php.
* Deny access to deploy.php.
I guess that public access to the migrate-database.php can be considered a security issue.
> Deny access to some files

- wp-content/plugins/ig-menu-help/plugin.php
* The Integreat Wiki link in the admin back end
is opened in a blank window. The target attribute
is not supported by the WP API and is therefore
added by a jQuery script.
* Fixes #898
> Add blank target to IG wiki link

- wp-content/plugins/ig-feedback/script.js
Prevents the default link action (jump to top) when clicking on the comments spoiler.
Fixes: #937
> [ig-feedback] prevent jump to top of page when spoiler is folded out (Resolves #937)

- .htaccess
* Disallow posting any content via the normal Wordpress
comment function to fix CVE-2019-9787.
> Disable normal comment content

- wp-content/plugins/ig-customize-login-integreat/customize-login-integreat.php
* We want to know which users logged in or failed
to do so in our centralized logging server.
* Creates the following two syslog messages:
```
2019-03-22T16:31:11.906976+01:00 server9 ool www: INTEGREAT CMS: svenseeberg from 2003:e1:2719:a300:52d7:cc72:3fad:36d6 logged in via https://cms-test.integreat-app.de/wp-login.php.
2019-03-22T16:32:25.203822+01:00 server9 ool www: INTEGREAT CMS: svenorganisation from 2003:e1:2719:a300:52d7:cc72:3fad:36d6 failed to log in via https://cms-test.integreat-app.de/wp-login.php.
```
@dkehne is logging the IP addresses of our back end users compliant with our data protection rules?
> Add syslog logging on (failed) log in

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
* If the header 'X-Integreat-Development' is set,
the API request will not be tracked for a single
site but only in the general statistics.
Example usage:
```
curl --header "X-Integreat-Development: True" http://integreat/testumgebung/de/wp-json/extensions/v3/pages
```
> Add HTTP header to prevent tracking

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Events.php
* For events, the web app uses the featured image with larger
resolution than the 150px * 150px thumbnail. Therefore we
need larger images. This commit adds the other preview sizes
(medium, large) and also the full size image URL to the
events APIv3 endpoint.
* Fixes #954 
* Adds the following object to each event in the APIv3, if an
featured image exists. Otherwise, the `featured_image` is `null`.
```
"featured_image": {
"medium": String, // URL to 300 px image
"large": String, // URL to 768px image
"full": String, // URL to full sized image
}
```
> Add all featured image sizes to events

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Post.php
Adds a `ltrim()` to the permalink because WPML does stupid things with translated permalinks and the function `url_to_postid()` does not work as expected on relative paths.
This way, either paths with leading slash or paths without them work.
I tested this on cms-test and it seems to work as expected.
Fixes #974
> Allow leading slashes of relative permalinks for feedback api endpoint

- wp-content/plugins/ig-settings/classes/IntegreatSetting.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
- Adds the option to add numbers as an "Integreat Setting". This is required to output longitude and latitude as defined in our APIv3 documentation.
> Add float numbers to Integreat settings

- wp-content/plugins/ig-settings/classes/IntegreatSettingConfig.php
- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
If the user does not enter an empty JSON object, the plugin can assume that {} is okay.
>  Change IG Settings empty JSON value

- wp-content/plugins/ig-wp-api-extensions/endpoints/helper/PiwikHelper.php
This change sends either "App" or "Web" as a user agent to the Matomo API. With that we can compare the usage of our Web App and Mobile App.
> Add Web/App User Agent to Matomo Tracking

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php
The function [`get_pages()`](https://developer.wordpress.org/reference/functions/get_pages/) seems to be very slow when executed multiple times within one request.
However, this function seems the go-to way to check whether an page has children [1], [2].
As a result, it does not seem justified to use this function just to determine if the content of a page is empty. We should rather drop the "empty"-string, because it is still clear that a page is empty by just seeing a blank page.
[1] https://wordpress.stackexchange.com/questions/73609/show-content-if-parent-page-has-children
[2] https://wordpress.stackexchange.com/questions/35724/function-to-return-true-if-current-page-has-child-pages?rq=1
> Speed up API by not checking for empty content

- wp-content/plugins/ig-attach-content/plugin.php
* Do not show disabled blogs in dropdown for attach content.
* This is not a secure features, it simply does not list disabled
sites.
**Fixes**: #1024
> Change attach content blog selection, fixes #1024

- wp-content/plugins/ig-settings/classes/IntegreatSettingsPlugin.php
Resolves the database error when retrieving the sites api which leads to missing fields
Fix sql syntax in ig-settings-api filter
> Fix sql syntax error in ig-settings-api filter

- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Abstract.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Feedback_Post.php
`url_to_postid()` breaks without host and procotol when the string contains Arabic or Farsi characters. Sanitizing the permalink URL by prepending the hostname, if required, fixes the issue.
> Sanitize Feedback permalink, fixes WP-10

- wp-content/plugins/firebase-notifications/plugin.php
- wp-content/plugins/ig-wp-api-extensions/endpoints/liveinstances.txt
* Only show Push Notifications in admin menu if Integreat Push Notifications are renabled.
* Drop legacy list of enabled locations.
> Add check for enabled FCM PN in admin Gui, fixes WP-12

- wp-content/plugins/tinymce-no-translate/no-translate.js
* Change `Text für Übersetzungen sperren` to `Wort für Übersetzungen sperren` to hint that the function is only intended for single words.
> Change no translate button title

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
- Fixes the problem that disabled sites appear in the sitemap
- Exclude sites from the sitemap if they are public, but disabled
**Fixes**: WP-15
> Exclude disabled sites from sitemap

- wp-content/plugins/tinymce-no-translate/plugin.php
* Change tinymce-no-translate plugin to allow translate attributes in span tags.
> Allow translate attribute for span, fixes WP-19

- wp-content/plugins/ig-sitemap/IntegreatSitemap.php
- This is also part of the problem that hidden sites show up in the search index (WP-15)
- return 404 when a crawler tries to find the "hidden" sitemap.xml files which are not included in the sitemap index
**Fixes**: WP-15
> Return 404 on sitemaps of hidden sites

- wp-content/plugins/ig-customize-editor-integreat/customize-editor-integreat.php
By default, if a parent page is draft or private, it is not available as a parent. We want all pages to be available as parents.
> Allow private/draft pages as parent

- wp-admin/about.php
- wp-admin/includes/media.php
- wp-admin/includes/misc.php
- wp-admin/themes.php
- wp-includes/pluggable.php
- wp-includes/version.php
Patch Worppress Core to fix some vulnerabilities. As far as I can tell, none of these vulnerabilities affect us, due to our special permissions structure. So this is just to be on the safe.
* Props to Sam Thomas (jazzy2fives) for finding an XSS issue where authenticated users with low privileges are able to add JavaScript to posts in the block editor
* Props to Luigi – (gubello.me) for discovering an XSS issue where authenticated users with upload permissions are able to add JavaScript to media files.
* Props to Ben Bidner of the WordPress Security Team for finding an open redirect issue in wp_validate_redirect()
* Props to Nrimo Ing Pandum for finding an authenticated XSS issue via theme uploads
* Props to Simon Scannell of RIPS Technologies for finding an issue where set-screen-option …
> Update WP to 4.9.15

- wp-content/plugins/ig-attach-content/plugin.php
- wp-content/plugins/ig-push-content/plugin.php
Only remove meta options for a page, if the POST contains the action=editpost variable.
- XLIFF import removes Push Content API tokens and live content.
> Fix WPML XLIFF import compatibility

- export-database.php
I noticed a few problems with the administrative division export of the regions:
- It is not correctly determined whether the AD is included in the full region name or not (field `administrative_division_included` is missing and thus always `False` by default)
- ADs "Kreis", "Stadt und Landkreis" and "Region" are incorrectly mapped to `MUNICIPALITY`
- Regions with no prefix are always mapped to `MUNICIPALITY`, even if "kreis" is contained in their name, e.g. "Alb-Donau-Kreis", "Lahn-Dill-Kreis" and many others
Fix the problems listed above
Please not that I currently don't have a working php dev setup, so I didn't test it out :wink:
> Fix administrative division in data export

- export-database.php
- Do not export pages that were only saved automatically as drafts.
> Export: ignore automatically saved drafts

- export-database.php
We only have to check page items where the post_type is revision and the parent the original post.
> Export: fix page revision status check

- export-database.php
This PR creates a file in /tmp during the database export that contains a map of WP slugs and Django translations. The format is `Region Slug;Page ID;Translation ID;Language ID;Version;WP Slug`.
Example:
```
stadtdachau;2622;63555;70;1;%e1%88%9d%e1%8a%bd%e1%88%aa
stadtdachau;2622;63556;70;2;%e1%88%9d%e1%8a%bd%e1%88%aa
stadtdachau;2623;63557;3;1;hilfsangebote
stadtdachau;2623;63558;3;2;hilfsangebote
stadtdachau;2623;63559;3;3;hilfsangebote
```
> Export: save slug mapping file

- export-database.php
The blog with ID 1 was originally the landing page and has no use for the Integreat app.
> Export: skip blog ID 1, fixes WP-69
